cmake_minimum_required(VERSION 3.16.0)
project(CUVIS.C.EXMPLES C)
add_subdirectory(Example_1_Take_Snapshot)
add_subdirectory(Example_2_Load_Measurement)
add_subdirectory(Example_3_Reprocess)
add_subdirectory(Example_4_Exporters)
add_subdirectory(Example_5_Record_Video)
add_subdirectory(Example_6_Record_Video_From_SessionFile)
add_subdirectory(Example_7_Change_Distance)
